CREATE TABLE [PROPIETARIOS](
    DNI INT NOT NULL,
    [name] VARCHAR(600) NOT NULL,
    [direccion] VARCHAR(600) NOT NULL

)
ALTER TABLE [PROPIETARIOS] ADD CONSTRAINT PX_Propietarios PRIMARY KEY (DNI)
GO
CREATE TABLE [LOCALES](
    CODIGO INT NOT NULL,
    DNI INT NOT NULL,
    [UBICACION] VARCHAR(600) NOT NULL,
    [SUPERFICIE] VARCHAR(600) NOT NULL

)
ALTER TABLE [LOCALES] ADD CONSTRAINT PX_Propietarios PRIMARY KEY (CODIGO)
GO