select cp.NUMPEDIDO, cp.CLI, cp.REP, cp.CLIENTE, cp.REPCLIE, cp.VENDEDOR, 
mp.FAB, mp.PRODUCTO, mp.CANT, mp.IMPORTE 
from CLIENTEPEDIDO as cp INNER JOIN MOVIMIENTOPEDIDO as mp on cp.NUMPEDIDO=mp.NUMPEDIDO